INSERT INTO "PUBLIC"."COUNTERPARTY"
("COUNTERPARTY_ID","IS_TAXPAYER","NAME","OWNERSHIP","REG_NUMBER","SHORT_NAME","TAX_NUMBER","TAXPAYER_LICENSE_NUMBER","TYPE")
VALUES(1,TRUE,'Lisnichenko','FOP','3049709419','FOP LISNICHENKO','11111','5555','FOP');

INSERT INTO "PUBLIC"."DOCUMENT"
("DOCUMENT_ID","COMMENTS","DATE_EXPIRATION","DATE_ISSUE","NUMBER","REGISTRATION","SERIES","TYPE","COUNTERPARTY_ID")
VALUES(1,'',null,parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),'530400','Samara','AK','PASSPORT',1);
INSERT INTO "PUBLIC"."DOCUMENT"
("DOCUMENT_ID","COMMENTS","DATE_EXPIRATION","DATE_ISSUE","NUMBER","REGISTRATION","SERIES","TYPE","COUNTERPARTY_ID")
VALUES(2,'',null,parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),'530444','Samara','AN','PASSPORT',1);

INSERT INTO  CONTACTS (CONTACTS_ID ,COMMENTS ,TYPE ,VALUES ,COUNTERPARTY_ID)
VALUES(1,'','PHONE','+380661111111',1);
INSERT INTO  CONTACTS (CONTACTS_ID ,COMMENTS ,TYPE ,VALUES ,COUNTERPARTY_ID)
VALUES(2,'','E_MAIL','EXAMPLE@EX.COM',1);

INSERT INTO FINANCE (FINANCE_ID ,ACCOUNT ,BANK_NAME_SHORTLY ,MFI ,COUNTERPARTY_ID )
VALUES(1,'00022255589966','PAO PRIVATBANK','0298456',1);

INSERT INTO FINANCE (FINANCE_ID ,ACCOUNT ,BANK_NAME_SHORTLY ,MFI ,COUNTERPARTY_ID )
VALUES(2,'00022342489966','PAO AVAL','03345456',1);

INSERT INTO ADDRESS (ADDRESS_ID ,COMMENTS ,APARTMENT ,BUILDING ,CITY ,COUNTRY ,FULL_ADDRESS ,REGION ,STREET ,TYPE ,ZIP_CODE ,COUNTERPARTY_ID )
VALUES(1,'','432-A','34','KIEV','UKRAINE','FULL','','FIRST STREET','LEGAL','79620',1);