
INSERT INTO "PUBLIC"."COUNTERPARTY"
("COUNTERPARTY_ID","IS_TAXPAYER","NAME","OWNERSHIP","REG_NUMBER","SHORT_NAME","TAX_NUMBER","TAXPAYER_LICENSE_NUMBER","TYPE",
"MAIN_COUNTERPARTY", "LAST_STATUS", "STATUS","SUB_TYPE")
VALUES(1,TRUE,'Lisnichenko','FOP','3044809452','FOP LISNICHENKO','11111','5555','FOP', null,parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),
'ACTIVE','OWNER');

INSERT INTO "PUBLIC"."COUNTERPARTY"
("COUNTERPARTY_ID","IS_TAXPAYER","NAME","OWNERSHIP","REG_NUMBER","SHORT_NAME","TAX_NUMBER","TAXPAYER_LICENSE_NUMBER","TYPE",
"MAIN_COUNTERPARTY", "LAST_STATUS", "STATUS","SUB_TYPE")
VALUES(2,TRUE,'Ivan','Ivanov','3657709486','Ivanovuch','11111','5555','DRIVER', 1,parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),
'ACTIVE','EMPLOYEE');

INSERT INTO "PUBLIC"."COUNTERPARTY"
("COUNTERPARTY_ID","IS_TAXPAYER","NAME","OWNERSHIP","REG_NUMBER","SHORT_NAME","TAX_NUMBER","TAXPAYER_LICENSE_NUMBER","TYPE",
"MAIN_COUNTERPARTY", "LAST_STATUS", "STATUS","SUB_TYPE")
VALUES(3,TRUE,'Lisnichenko','FOP','30485799579','FOP LISNICHENKO','11111','5555','FOP', null,parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),
'ACTIVE','CUSTOMER');

INSERT INTO "PUBLIC"."DOCUMENT"
("DOCUMENT_ID","COMMENTS","DATE_EXPIRATION","DATE_ISSUE","NUMBER","REGISTRATION","SERIES","TYPE","COUNTERPARTY_ID")
VALUES(1,'',null,parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),'530400','Samara','AK','PASSPORT',1);
INSERT INTO "PUBLIC"."DOCUMENT"
("DOCUMENT_ID","COMMENTS","DATE_EXPIRATION","DATE_ISSUE","NUMBER","REGISTRATION","SERIES","TYPE","COUNTERPARTY_ID")
VALUES(2,'',null,parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),'530444','Samara','AN','PASSPORT',2);

INSERT INTO  CONTACTS (CONTACTS_ID ,COMMENTS ,TYPE ,VALUES ,COUNTERPARTY_ID)
VALUES(1,'','PHONE','+380661111111',1);
INSERT INTO  CONTACTS (CONTACTS_ID ,COMMENTS ,TYPE ,VALUES ,COUNTERPARTY_ID)
VALUES(2,'','E_MAIL','EXAMPLE@EX.COM',1);

INSERT INTO FINANCE (FINANCE_ID ,ACCOUNT ,BANK_NAME_SHORTLY ,MFI ,COUNTERPARTY_ID )
VALUES(1,'00022255589966','PAO PRIVATBANK','0298456',1);

INSERT INTO FINANCE (FINANCE_ID ,ACCOUNT ,BANK_NAME_SHORTLY ,MFI ,COUNTERPARTY_ID )
VALUES(2,'00022342489966','PAO AVAL','03345456',1);

INSERT INTO ADDRESS (ADDRESS_ID ,COMMENTS ,APARTMENT ,BUILDING ,CITY ,COUNTRY ,FULL_ADDRESS ,REGION ,STREET ,TYPE ,ZIP_CODE ,COUNTERPARTY_ID )
VALUES(1,'','432-A','34','KIEV','UKRAINE','FULL','','FIRST STREET','LEGAL','79620',1);
